# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cleaner CI

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_PROJECT_ID: ${{ secrets.GAR_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_SERVICE: ${{ secrets.GAR_SERVICE }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  SERVICE: ${{ secrets.SERVICE }}
  REGION: ${{ secrets.REGION }}

jobs:
  artifact-registry-cleaner:
    environment: prod

    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Clear Artifact Registry
        uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.GAR_SERVICE }}
            -grace=48h
            -keep=2
            -dry_run=true
